### PR TITLE
Splash Page Design

### LINKED ISSUE #57: Design splash page

### PR DESCRIPTION
**Pull request by Bryonnab**
- Designed and integrated the splash page for laptop resolution and above (min-width: 1200px) 
- Updated the site title 

close #57, #61, #59, 
attributes to #60

### CODE REVIEW

**Review by GarettOS — APPROVED** [review]

**Review by walshb421 — COMMENTED** [review]
When I zoom out this looks perfect.
image

But by default when I open it things seem a little off probably because my screen is smaller.
image

**Comment by Bryonnab** [comment]
Good to go for review

**Review by walshb421 — APPROVED** [review]
This is looking great!

**Review by GarettOS — APPROVED** [review]
Looks good dude!

**Pull request merged**
